// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91BCVMSBq2sLDY4REWCvR9bLyNf_4858',
    appId: '1:985292783122:web:38fe72014fefc2cccf22cb',
    messagingSenderId: '985292783122',
    projectId: 'premedq',
    authDomain: 'premedq.firebaseapp.com',
    storageBucket: 'premedq.firebasestorage.app',
    measurementId: 'G-0QLDSHSKYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-TCVltu3X2S6bpZKU_ChbmwN0c6n_6tg',
    appId: '1:985292783122:android:b036c747c2033963cf22cb',
    messagingSenderId: '985292783122',
    projectId: 'premedq',
    storageBucket: 'premedq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnQD6sulIeAJUbT4wlYp6NOCX_6FV0XU',
    appId: '1:985292783122:ios:9e0c51e5441bab9ecf22cb',
    messagingSenderId: '985292783122',
    projectId: 'premedq',
    storageBucket: 'premedq.firebasestorage.app',
    iosClientId: '985292783122-mg9tf3kpgjgltjjvbes9vfql6eeerpjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.medq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnQD6sulIeAJUbT4wlYp6NOCX_6FV0XU',
    appId: '1:985292783122:ios:9e0c51e5441bab9ecf22cb',
    messagingSenderId: '985292783122',
    projectId: 'premedq',
    storageBucket: 'premedq.firebasestorage.app',
    iosClientId: '985292783122-mg9tf3kpgjgltjjvbes9vfql6eeerpjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.medq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD91BCVMSBq2sLDY4REWCvR9bLyNf_4858',
    appId: '1:985292783122:web:9905150a7e50c62ecf22cb',
    messagingSenderId: '985292783122',
    projectId: 'premedq',
    authDomain: 'premedq.firebaseapp.com',
    storageBucket: 'premedq.firebasestorage.app',
    measurementId: 'G-V7HCHSWJQ3',
  );
}
